name: "Google Chat SaWrong"
description: "Send a message to Google Chat via incoming webhook"

inputs:
  webhook_url:
    description: "Google Chat incoming webhook URL"
    required: true
  message:
    description: "Message text to send"
    required: true
  title:
    description: "Optional title prefix (e.g., 'CI', 'Deploy')"
    required: false
    default: ""
  include_job_context:
    description: "If true, appends repo/workflow/run info"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Send to Google Chat
      shell: bash
      env:
        INPUT_WEBHOOK_URL: ${{ inputs.webhook_url }}
        INPUT_MESSAGE: ${{ inputs.message }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_INCLUDE_JOB_CONTEXT: ${{ inputs.include_job_context }}
      run: |
        set -euo pipefail
        chmod +x "$GITHUB_ACTION_PATH/send.sh"
        "$GITHUB_ACTION_PATH/send.sh"
