name: "Google Chat Webhook Notify"
description: "Send a message to Google Chat via incoming webhook"

inputs:
  webhook_url:
    description: "Google Chat incoming webhook URL"
    required: true
  message:
    description: "Message text to send"
    required: true
  title:
    description: "Optional title prefix (e.g., 'CI', 'Deploy')"
    required: false
    default: ""
  include_job_context:
    description: "If true, appends repo/workflow/run info"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Build payload
      id: payload
      shell: bash
      run: |
        set -euo pipefail

        msg="${{ inputs.message }}"
        title="${{ inputs.title }}"
        include_ctx="${{ inputs.include_job_context }}"

        if [[ -n "${title}" ]]; then
          msg="[$title] $msg"
        fi

        if [[ "${include_ctx}" == "true" ]]; then
          footer="$(cat <<EOF

Repository: ${GITHUB_REPOSITORY}
Workflow: ${GITHUB_WORKFLOW}
Run: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
Ref: ${GITHUB_REF}
EOF
)"
          msg="${msg}${footer}"
        fi

        export MSG="$msg"
        payload="$(python3 - <<'PY'
import json, os
msg = os.environ["MSG"]
print(json.dumps({"text": msg}, ensure_ascii=False))
PY
)"
        {
          echo "payload<<__PAYLOAD__"
          echo "$payload"
          echo "__PAYLOAD__"
        } >> "$GITHUB_OUTPUT"

    - name: Send to Google Chat
      shell: bash
      run: |
        set -euo pipefail
        curl -sS -X POST \
          -H "Content-Type: application/json" \
          -d '${{ steps.payload.outputs.payload }}' \
          '${{ inputs.webhook_url }}'
